#!/bin/sh
# Push with hooks
# http://stackoverflow.com/questions/1797074/local-executing-hook-after-a-git-push/3812238#3812238

GIT_DIR_="$(git rev-parse --git-dir)"
BRANCH="$(git rev-parse --symbolic --abbrev-ref $(git symbolic-ref HEAD))"

PRE_PUSH="$GIT_DIR_/hooks/pre-push"
POST_PUSH="$GIT_DIR_/hooks/post-push"

test -x "$PRE_PUSH" &&
      exec "$PRE_PUSH" "$BRANCH" "$@"

git push "$@"

test $? -eq 0 && test -x "$POST_PUSH" &&
      exec "$POST_PUSH" "$BRANCH" "$@"
